In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_excel("Business Analyst Assignment New.xlsx")

In [36]:
df.head(3)

,lead_date,RTO Codes,lead_reg,book_reg,bookedinsurer,totalpremium,Bookedplantype,utmmedium,utmcampaign,utmterm,...,Reg_date,ccGroup,Segment,Make,Model,Variant,State,City,Vehicle_Age,carinfo_expirydt
0,2025-03-04,AN,1,0,NaN,NaN,NaN,challan_detail_flutter,challan_detail_flutter_PB_BIKE_1_false,header,...,2008-12-23,76-150 CC,BIKE,Honda,Shine,Kick Start Drum Brake Alloy Wheels (125 cc),Andaman and Nicobar Islands,Port Blair,16,2025-03-06 00:00:00
1,2025-03-02,AP,0,0,NaN,NaN,NaN,rc_detail,rc_detail_PB_BIKE_1_false,imp_dates_GARAGE_false,...,2019-03-01,76-150 CC,BIKE,Bajaj,Pulsar 150 Dtsi,Kick Start (150 cc),Andhra Pradesh,Kadapa,6,2019-06-10 00:00:00
2,2025-03-04,AP,1,0,NaN,NaN,NaN,input_ins_natv,input_ins_natv_PB_BIKE_1_false,input_carousel,...,2011-12-05,76-150 CC,BIKE,Hero Motocorp,Splendor Pro,Kick Start Drum Brake Cast Wheels (100 cc),Andhra Pradesh,Kakinada,13,2012-11-22 00:00:00

In [37]:
df.shape

(73907, 23)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73907 entries, 0 to 73906
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lead_date         73907 non-null  datetime64[ns]
 1   RTO Codes         73907 non-null  object
 2   lead_reg          73907 non-null  int64
 3   book_reg          73907 non-null  int64
 4   bookedinsurer     2184 non-null   object
 5   totalpremium      2184 non-null   float64
 6   Bookedplantype    2184 non-null   object
 7   utmmedium         73900 non-null  object
 8   utmcampaign       73880 non-null  object
 9   utmterm           73903 non-null  object
 10  devicesource      73907 non-null  object
 11  utm_content       61125 non-null  object
 12  Reg_Year          73907 non-null  int64
 13  Reg_date          73907 non-null  datetime64[ns]
 14  ccGroup           73907 non-null  object
 15  Segment           73907 non-null  object
 16  Make              73907 non-null  object
 17  Model             73907 non-null  object
 18  Variant           73907 non-null  object
 19  State             73889 non-null  object
 20  City              73889 non-null  object
 21  Vehicle_Age       73907 non-null  int64
 22  carinfo_expirydt  73907 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(4), object(16)
memory usage: 13.0+ MB

In [67]:
df['book_reg'].value_counts()

book_reg
0    71723
1     2184
Name: count, dtype: int64

In [39]:
(df.isna().sum()/len(df)*100).sort_values(ascending=False)

# bookedinsurer, totalpremium and Bookedplantype have around 97% missing values
# these are expected because they are only available for booked policies

bookedinsurer       97.044935
totalpremium        97.044935
Bookedplantype      97.044935
utm_content         17.294708
utmcampaign          0.036532
City                 0.024355
State                0.024355
utmmedium            0.009471
utmterm              0.005412
Segment              0.000000
Vehicle_Age          0.000000
Variant              0.000000
Model                0.000000
Make                 0.000000
lead_date            0.000000
ccGroup              0.000000
Reg_date             0.000000
Reg_Year             0.000000
RTO Codes            0.000000
devicesource         0.000000
book_reg             0.000000
lead_reg             0.000000
carinfo_expirydt     0.000000
dtype: float64

In [40]:
df.duplicated().sum()

12

In [41]:
df.describe()

# this is statistical summary

,lead_date,lead_reg,book_reg,totalpremium,Reg_Year,Reg_date,Vehicle_Age
count,73907,73907.000000,73907.000000,2184.000000,73907.000000,73907,73907.000000
mean,2025-03-03 00:49:12.986861824,0.801156,0.029551,995.585623,2016.422463,2016-11-19 11:04:06.618046976,8.307048
min,2025-03-01 00:00:00,0.000000,0.000000,100.000000,1900.000000,1900-01-01 00:00:00,0.000000
25%,2025-03-02 00:00:00,1.000000,0.000000,843.000000,2014.000000,2014-08-01 00:00:00,5.000000
50%,2025-03-03 00:00:00,1.000000,0.000000,856.000000,2017.000000,2017-12-13 00:00:00,7.000000
75%,2025-03-04 00:00:00,1.000000,0.000000,930.250000,2020.000000,2020-01-24 00:00:00,11.000000
max,2025-03-05 00:00:00,1.000000,1.000000,6601.000000,2025.000000,2025-03-05 00:00:00,125.000000
std,NaN,0.399133,0.169345,420.559628,7.027412,NaN,7.030624

In [42]:
# categorical summary

df.describe(include="object")

,RTO Codes,bookedinsurer,Bookedplantype,utmmedium,utmcampaign,utmterm,devicesource,utm_content,ccGroup,Segment,Make,Model,Variant,State,City,carinfo_expirydt
count,73907,2184,2184,73900,73880,73903,73907,61125,73907,73907,73907,73907,73907,73889,73889,73907
unique,42,16,3,33,94,61,4,3,4,2,72,410,894,37,1020,7332
top,UP,NIC,Comp,rc_detail,rc_detail_PB_BIKE_1_false,header,Mobile,express_check_comp,76-150 CC,BIKE,Hero Motocorp,Splendor Plus,DX (100 cc),Uttar Pradesh,New Delhi,2025-03-04 00:00:00
freq,13227,444,1182,39232,34733,8363,72812,54648,59004,53577,18888,7454,5389,13231,2951,1077

In [43]:
df.nunique()

lead_date              5
RTO Codes             42
lead_reg               2
book_reg               2
bookedinsurer         16
totalpremium         478
Bookedplantype         3
utmmedium             33
utmcampaign           94
utmterm               61
devicesource           4
utm_content            3
Reg_Year              51
Reg_date            7399
ccGroup                4
Segment                2
Make                  72
Model                410
Variant              894
State                 37
City                1020
Vehicle_Age           50
carinfo_expirydt    7332
dtype: int64

Data Cleaning

In [44]:
df1 = df.copy()

In [45]:
# removing duplicate rows
df1.drop_duplicates(inplace=True)

In [46]:
# Convert date columns

date_cols = ["lead_date","Reg_date","carinfo_expirydt"]
for col in date_cols:
    df1[col] = pd.to_datetime(df1[col],errors="coerce")

In [47]:
# Convert premium to numeric

df1["totalpremium"] = pd.to_numeric(df1["totalpremium"],errors="coerce")

In [48]:
# Remove extra spaces

obj_cols = df1.select_dtypes(include="object").columns
for col in obj_cols:
    df1[col] = df1[col].str.strip()

In [49]:
# Standardizing the text

text_cols = [
    "bookedinsurer",
    "Bookedplantype",
    "utmmedium",
    "utmcampaign",
    "Make",
    "Model",
    "City",
    "State",
    "ccGroup",
    "Segment"
]

for col in text_cols:
    df1[col] = df1[col].str.title()

In [50]:
# Missing values after cleaning

((df1.isna().sum()/len(df1)*100).sort_values(ascending=False))

# Missing values in bookedinsurer, Bookedplantype and totalpremium
# are valid because those leads were not converted into bookings

Bookedplantype      97.044455
bookedinsurer       97.044455
totalpremium        97.044455
utm_content         17.296163
utmcampaign          0.645511
utmmedium            0.622505
carinfo_expirydt     0.027065
State                0.024359
City                 0.024359
utmterm              0.005413
Model                0.002707
book_reg             0.000000
lead_reg             0.000000
devicesource         0.000000
RTO Codes            0.000000
Reg_Year             0.000000
Reg_date             0.000000
ccGroup              0.000000
Segment              0.000000
Make                 0.000000
Variant              0.000000
Vehicle_Age          0.000000
lead_date            0.000000
dtype: float64

In [51]:
df1.head(3)

,lead_date,RTO Codes,lead_reg,book_reg,bookedinsurer,totalpremium,Bookedplantype,utmmedium,utmcampaign,utmterm,...,Reg_date,ccGroup,Segment,Make,Model,Variant,State,City,Vehicle_Age,carinfo_expirydt
0,2025-03-04,AN,1,0,NaN,NaN,NaN,Challan_Detail_Flutter,Challan_Detail_Flutter_Pb_Bike_1_False,header,...,2008-12-23,76-150 Cc,Bike,Honda,Shine,Kick Start Drum Brake Alloy Wheels (125 cc),Andaman And Nicobar Islands,Port Blair,16,2025-03-06
1,2025-03-02,AP,0,0,NaN,NaN,NaN,Rc_Detail,Rc_Detail_Pb_Bike_1_False,imp_dates_GARAGE_false,...,2019-03-01,76-150 Cc,Bike,Bajaj,Pulsar 150 Dtsi,Kick Start (150 cc),Andhra Pradesh,Kadapa,6,2019-06-10
2,2025-03-04,AP,1,0,NaN,NaN,NaN,Input_Ins_Natv,Input_Ins_Natv_Pb_Bike_1_False,input_carousel,...,2011-12-05,76-150 Cc,Bike,Hero Motocorp,Splendor Pro,Kick Start Drum Brake Cast Wheels (100 cc),Andhra Pradesh,Kakinada,13,2012-11-22

In [52]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73895 entries, 0 to 73906
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lead_date         73895 non-null  datetime64[ns]
 1   RTO Codes         73895 non-null  object
 2   lead_reg          73895 non-null  int64
 3   book_reg          73895 non-null  int64
 4   bookedinsurer     2184 non-null   object
 5   totalpremium      2184 non-null   float64
 6   Bookedplantype    2184 non-null   object
 7   utmmedium         73435 non-null  object
 8   utmcampaign       73418 non-null  object
 9   utmterm           73891 non-null  object
 10  devicesource      73895 non-null  object
 11  utm_content       61114 non-null  object
 12  Reg_Year          73895 non-null  int64
 13  Reg_date          73895 non-null  datetime64[ns]
 14  ccGroup           73895 non-null  object
 15  Segment           73895 non-null  object
 16  Make              73895 non-null  object
 17  Model             73893 non-null  object
 18  Variant           73895 non-null  object
 19  State             73877 non-null  object
 20  City              73877 non-null  object
 21  Vehicle_Age       73895 non-null  int64
 22  carinfo_expirydt  73875 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(4), object(15)
memory usage: 13.5+ MB

In [53]:
df1.to_csv("cleaned_insurance_data.csv",index=False)

Exploratory Data Analysis

In [54]:
# Total Leads
total_leads = df1["lead_reg"].notna().sum()

# Total Bookings
total_bookings = df1["book_reg"].notna().sum()

# Conversion Rate
conversion_rate = (total_bookings/total_leads)*100

# Total Revenue
total_revenue = df1["totalpremium"].sum()

# Average Premium
average_premium = df1["totalpremium"].mean()

# Lead Drop-off
drop_off = total_leads-total_bookings

In [55]:
# KPI

print("Total Leads :",total_leads)
print("Total Bookings :",total_bookings)
print(f"Conversion Rate : {conversion_rate:.2f}%")
print("Lead Drop-off :",drop_off)
print("Total Revenue :",round(total_revenue,2))
print("Average Premium :",round(average_premium,2))

Total Leads : 73895
Total Bookings : 73895
Conversion Rate : 100.00%
Lead Drop-off : 0
Total Revenue : 2174359.0
Average Premium : 995.59

In [56]:
# Top Insurers
print("Top Insurers by Revenue")
df1.groupby("bookedinsurer")["totalpremium"].sum().sort_values(ascending=False)

Top Insurers by Revenue

bookedinsurer
Nic              458128.0
Icici Lombard    391496.0
Bagic            291823.0
United           252847.0
Digit            251764.0
Sbi              128822.0
Nia               97620.0
Tata Aig          78592.0
Reliance          78229.0
Itgi              66863.0
Kotak             33096.0
Oicl              31468.0
Zuno              10256.0
Rsgi               1513.0
Chola               976.0
Sgi                 866.0
Name: totalpremium, dtype: float64

In [57]:
# Top Plan Types
print("Top Plan Types by Revenue")
df1.groupby("Bookedplantype")["totalpremium"].sum().sort_values(ascending=False)

Top Plan Types by Revenue

Bookedplantype
Comp    1288423.0
Tp       793373.0
Od        92563.0
Name: totalpremium, dtype: float64

In [58]:
# Marketing Medium
print("Bookings by UTM Medium")
df1[df1["book_reg"].notna()].groupby("utmmedium").size().sort_values(ascending=False)

Bookings by UTM Medium

utmmedium
Rc_Detail                 39232
Homepage                   9644
Challan_Detail_Flutter     8363
Default                    4942
Challan_Details            3475
Home_Screen                2895
Default_Screen             1530
Default_Src                1088
Det_Ins_Natv                584
My_Garage                   541
Rc_Home                     372
Input_Ins_Natv              184
Ins_Natv                    131
Notification                108
Insurance_Native             83
Web_Challan_Hp               66
Universal_Search             50
Services                     45
Nullquote                    36
Service_Page                 26
Car-Info_Web                 11
Challan_Detail                7
Ins_Homepage_V3               4
Wpcampaignthreenew            4
Notificationnew               3
Challan_Screen                3
Nudge                         2
Web_Homepage                  2
Rc                            1
Insurance                     1
Header                        1
Wpcampaignbike                1
dtype: int64

In [59]:
# Revenue by UTM Medium
print("Revenue by UTM Medium")
df1.groupby("utmmedium")["totalpremium"].sum().sort_values(ascending=False)

Revenue by UTM Medium

utmmedium
Rc_Detail                 1322244.0
Homepage                   336085.0
Home_Screen                109173.0
Default_Screen             105678.0
Challan_Detail_Flutter      83491.0
Default_Src                 42151.0
Det_Ins_Natv                37560.0
Default                     26355.0
Rc_Home                     14664.0
Challan_Details             13177.0
My_Garage                   12781.0
Notification                 4561.0
Insurance_Native             2600.0
Services                     1686.0
Universal_Search              843.0
Service_Page                  843.0
Car-Info_Web                  784.0
Wpcampaignthreenew            784.0
Web_Challan_Hp                480.0
Ins_Natv                      378.0
Challan_Detail                  0.0
Insurance                       0.0
Notificationnew                 0.0
Nudge                           0.0
Nullquote                       0.0
Rc                              0.0
Ins_Homepage_V3                 0.0
Input_Ins_Natv                  0.0
Header                          0.0
Challan_Screen                  0.0
Web_Homepage                    0.0
Wpcampaignbike                  0.0
Name: totalpremium, dtype: float64

In [60]:
# Campaign Performance

campaign = df1.groupby("utmcampaign").agg(
    Leads=("lead_reg","count"),
    Bookings=("book_reg",lambda x:x.notna().sum()),
    Revenue=("totalpremium","sum")
)

In [61]:
campaign["Conversion %"] = round((campaign["Bookings"]/campaign["Leads"])*100,2)
campaign["Drop-off"] = campaign["Leads"]-campaign["Bookings"]

print("Top Campaign Performance")
print(campaign.sort_values("Revenue",ascending=False).head(10))

Top Campaign Performance
                                        Leads  Bookings    Revenue  \
utmcampaign
Rc_Detail_Pb_Bike_1_False               34733     34733  1250231.0
Homepage_Defaultelig_False               3837      3837   126918.0
Homepage_Pb_Bike_1_False                 3765      3765   115159.0
Staticurl                                2228      2228   109385.0
_Defaultelig                             1530      1530   105678.0
Home_Screen_Pb_Bike_1_False              2766      2766   102284.0
Challan_Detail_Flutter_Pb_Bike_1_False   8103      8103    79600.0
Default_Src_Pb_Bike_1_False              1022      1022    39507.0
Det_Ins_Natv_Pb_Bike_1_False              530       530    36716.0
Rc_Detail_M_Bjaz_E_False                  903       903    28948.0

                                        Conversion %  Drop-off
utmcampaign
Rc_Detail_Pb_Bike_1_False                      100.0         0
Homepage_Defaultelig_False                     100.0         0
Homepage_Pb_Bike_1_False                       100.0         0
Staticurl                                      100.0         0
_Defaultelig                                   100.0         0
Home_Screen_Pb_Bike_1_False                    100.0         0
Challan_Detail_Flutter_Pb_Bike_1_False         100.0         0
Default_Src_Pb_Bike_1_False                    100.0         0
Det_Ins_Natv_Pb_Bike_1_False                   100.0         0
Rc_Detail_M_Bjaz_E_False                       100.0         0

In [62]:
# Vehicle Age
print("Bookings by Vehicle Age")
df1[df1["book_reg"].notna()].groupby("Vehicle_Age").size().sort_values(ascending=False)

Bookings by Vehicle Age

Vehicle_Age
5      9184
6      8886
7      7885
8      6289
9      5306
10     4534
11     3970
2      3869
1      3549
12     3373
3      3216
13     3011
14     2412
4      2063
15     1671
16     1077
17      785
18      591
19      418
20      336
21      221
22      167
125     152
23      148
24      144
0       127
25      125
26       75
27       61
28       49
29       43
30       33
31       23
34       21
32       19
35       19
33       13
36        9
37        5
39        4
44        2
38        2
40        1
43        1
46        1
49        1
52        1
53        1
57        1
63        1
dtype: int64

In [63]:
# Vehicle Made
print("Top Vehicle Makes")
df1[df1["book_reg"].notna()].groupby("Make").size().sort_values(ascending=False).head(10)

Top Vehicle Makes

Make
Hero Motocorp    18882
Bajaj            11684
Honda            10873
Tvs               7679
Kinetic           5450
Hero Honda        5244
Royal Enfield     5094
Yamaha            4502
Suzuki            2326
Ktm                608
dtype: int64

In [64]:
# Vehicle Model
print("Top Vehicle Models")
df1[df1["book_reg"].notna()].groupby("Model").size().sort_values(ascending=False).head(10)

Top Vehicle Models

Model
Splendor Plus      7450
Honda              5386
Activa             3146
Hf Deluxe          2744
Classic            2556
Apache             2244
Pulsar 150 Dtsi    1928
Super Splendor     1876
Passion Pro        1841
Glamour            1797
dtype: int64

In [65]:
# City Analysis
print("Top Cities")
df1[df1["book_reg"].notna()].groupby("City").size().sort_values(ascending=False).head(10)

Top Cities

City
New Delhi      2950
Patna           955
Surat           911
Lucknow         855
Pune            755
Ghaziabad       726
Kanpur          615
Bengaluru       593
Murshidabad     572
Coimbatore      561
dtype: int64

In [66]:
# CC Group Purchase Rate
cc_group = df1.groupby("ccGroup").agg(
    Leads=("lead_reg","count"),
    Bookings=("book_reg",lambda x:x.notna().sum())
)

cc_group["Purchase Rate %"] = round((cc_group["Bookings"]/cc_group["Leads"])*100,2)

print("CC Group Purchase Rate")
print(cc_group.sort_values("Purchase Rate %",ascending=False))

CC Group Purchase Rate
            Leads  Bookings  Purchase Rate %
ccGroup
151-350 Cc  12481     12481            100.0
76-150 Cc   58992     58992            100.0
<=75 Cc      1344      1344            100.0
>351 Cc      1078      1078            100.0